# Tensors

In [28]:
import torch
import numpy as np

## Intialize Tensor

### Data to Tensor

In [29]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


### NumPy array to Tensor

In [30]:
np_array=np.array(data)
x_np=torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


### Tensor to Tensor

If you create a new tensor based on another tensor, the new tensor will retain the properties (shape, datatype) of the original tensor. However, they could be changed by overriding the properties.

In [31]:
x_ones=torch.ones_like(x_data)
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [32]:
x_rand=torch.rand_like(x_data,dtype=torch.float) # override the datatype
print(x_rand)

tensor([[0.0303, 0.9029],
        [0.9559, 0.3212]])


### Random or Constant value

By using `shape` parameter, you can create a tensor with the shape and value you want.

In [33]:
shape=(2,3,)

In [34]:
rand_tensor=torch.rand(shape)
print(rand_tensor)

tensor([[0.9750, 0.7265, 0.9396],
        [0.7254, 0.0062, 0.3218]])


In [35]:
ones_tensor=torch.ones(shape)
print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [36]:
zeros_tensor=torch.zeros(shape)
print(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a Tensor

Tensor attributes are:
- shape
- datatype
- device

In [37]:
tensor=torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors

Operations on tensors are similar to NumPy arrays.
Operations are faster when using GPU(cuda).

In [38]:
# Use cuda to speed up the operations
if torch.cuda.is_available():
    tensor=tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


### indexing and slicing

In [53]:
tensor=torch.ones(4,4)
tensor[:,1]=0
tensor[1][2]=3
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 3., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### concatenate tensors

We can concatenate a sequence of tensors by using `torch.cat`.

In [51]:
tensor1=torch.tensor([[1,2,3],
                      [2,3,4],
                      [3,4,5]])
tensor2=torch.tensor([[[1,2,3],
                       [2,3,4],
                       [3,4,5]],
                      [[2,3,4],
                       [3,4,5],
                       [4,5,6]],
                      [[3,4,5],
                       [4,5,6],
                       [5,6,7]]])
t1=torch.cat([tensor1,tensor2[:,-1]],dim=0)
print(t1)
t2=torch.cat([tensor1,tensor2[:,-1]],dim=1)
print(t2)

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [3, 4, 5],
        [4, 5, 6],
        [5, 6, 7]])
tensor([[1, 2, 3, 3, 4, 5],
        [2, 3, 4, 4, 5, 6],
        [3, 4, 5, 5, 6, 7]])


### Arithmetic operations

We can perform arithmetic operations on tensors.
For example, matrix multiplication, element-wise multiplication, etc.

#### Matrix Multiplication

In [58]:
y1 = tensor @ tensor.T # @ is used for matrix multiplication and T is used for transpose
print(y1)

tensor([[ 3.,  5.,  3.,  3.],
        [ 5., 11.,  5.,  5.],
        [ 3.,  5.,  3.,  3.],
        [ 3.,  5.,  3.,  3.]])


In [59]:
y2 = tensor.matmul(tensor.T)
print(y2)

tensor([[ 3.,  5.,  3.,  3.],
        [ 5., 11.,  5.,  5.],
        [ 3.,  5.,  3.,  3.],
        [ 3.,  5.,  3.,  3.]])


In [57]:
y3 = torch.zeros_like(tensor)
torch.matmul(tensor, tensor.T, out=y3) # we can provide the output tensor
print(y3)

tensor([[ 3.,  5.,  3.,  3.],
        [ 5., 11.,  5.,  5.],
        [ 3.,  5.,  3.,  3.],
        [ 3.,  5.,  3.,  3.]])


#### Element-wise product

In [60]:
z1 = tensor * tensor
print(z1)

tensor([[1., 0., 1., 1.],
        [1., 0., 9., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [61]:
z2 = tensor.mul(tensor)
print(z2)

tensor([[1., 0., 1., 1.],
        [1., 0., 9., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [62]:
z3 = torch.zeros_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 9., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### Single-element tensors

We can itemize a single element tensor to Python numerical value by using `item()`.

In [65]:
agg=tensor.sum()
print(agg)

tensor(14.)


In [66]:
agg_item=agg.item()
print(agg_item,type(agg_item))

14.0 <class 'float'>


### In-place operations

We can perform in-place operations by using `_` suffix.

In [67]:
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 3., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [68]:
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 8., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [69]:
tensor.sub_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 3., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## Bridge with NumPy

We can associate a Tensor with a NumPy array which means that they share the same memory location and changing one will change the other.

### Tensor to NumPy array

In [82]:
t = torch.ones((2,3,4,))
print(t)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [83]:
n = t.numpy()
print(n)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [84]:
t.add_(1)
print(n)

[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


In [85]:
n[0,1]=7
print(t)

tensor([[[2., 2., 2., 2.],
         [7., 7., 7., 7.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]])


### NumPy array to Tensor

In [90]:
n = np.arange(12).reshape(-1,3,4)
print(n)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [91]:
t=torch.from_numpy(n)
print(t)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]], dtype=torch.int32)


In [92]:
np.add(n,1,out=n)
print(t)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]], dtype=torch.int32)
